version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=mydatabase
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  redis:
    image: redis:7.0
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
